### PR TITLE
Master

### PR DESCRIPTION
**Pull request by zzmicer**
Shkadarevich Dmitry, group 853506

### CODE REVIEW

**Comment by zzmicer** [comment]
I know that it's not a game, but I hope I've implemented key features you want.

Снимок экрана (283)
Снимок экрана (284)
photo_2021-01-03_13-42-31
photo_2021-01-03_13-42-44
photo_2021-01-03_13-42-14

**Comment by gmltA** [comment]
Wait a second. Did we discussed your personal task?

**Comment by zzmicer** [comment]
> Wait a second. Did we discussed your personal task?

No we didn't, should I redo?

**Comment by gmltA** [comment]
So you just decided not to make the thing that was asked and just did something else?

**Comment by zzmicer** [comment]
I'm very sorry, I thought I've implemented lab's key features in a different way. I misinterpreted task.

**Comment by zzmicer** [comment]
Can I modify this project in some way or should I create new one?

**Pull request merged**
